const ipsum = `Morbi vestibulum orci dolor, nec suscipit lectus commodo ut. Vivamus tristique tempus porttitor. Aliquam ultricies vel tortor vel sollicitudin. Mauris quis varius odio. Aenean pulvinar dolor at nulla suscipit, in mollis felis luctus. Curabitur et aliquam nulla. In hac habitasse platea dictumst. Sed viverra, risus in semper scelerisque, lorem turpis lacinia lectus, a pellentesque sem enim eget nulla. Suspendisse non eros orci. Morbi pulvinar aliquet turpis, sit amet malesuada leo pretium in.

Nullam quam urna, varius id pellentesque ac, rutrum vitae purus. Nulla venenatis quam magna, quis tincidunt ligula facilisis fermentum. Nam in iaculis nisi. In vitae libero placerat lorem interdum dictum. In dignissim massa eros, sagittis placerat felis eleifend ac. Integer blandit, sem vel vehicula lacinia, arcu erat rhoncus ligula, lacinia pellentesque nisi nibh a massa. Curabitur eget auctor justo. Donec suscipit sollicitudin ligula eu lobortis. Integer vehicula non dui at dapibus. Morbi ligula nisi, dignissim sed ligula id, faucibus cursus neque. Vivamus nec consequat lacus, id venenatis odio. Mauris eu est turpis. Integer enim nulla, venenatis non gravida a, mollis sit amet nunc.

Cras in aliquet odio. Nam quis lobortis turpis, eu auctor felis. Nulla id feugiat justo. Mauris dui orci, posuere et quam finibus, pretium sodales mauris. Nulla laoreet quam in justo pellentesque, eget porta purus egestas. Duis vel mollis justo. Donec sed nisi a leo fermentum lacinia. Ut finibus diam ut turpis placerat, vel pellentesque mauris aliquam. Phasellus sed mollis nunc.

In ultricies lacus eros, non maximus metus blandit vel. Vivamus porta venenatis risus, eget dapibus libero vehicula sit amet. Praesent vitae nisl tristique, faucibus neque a, imperdiet massa. Curabitur vel metus at massa efficitur pretium. Nulla nec lorem et nibh iaculis bibendum. Etiam rhoncus venenatis est et molestie. Cras massa velit, ullamcorper at odio et, tempus feugiat erat. Nulla congue eu turpis eu bibendum. In ut pellentesque est. Aliquam sit amet mi at mi vehicula vulputate. Suspendisse dignissim varius vestibulum. Sed lobortis tempus egestas. Vestibulum fermentum nisl eros, ac consequat justo semper eget.

Aliquam nec ullamcorper lorem, venenatis congue nisl. Phasellus vestibulum nunc id nulla feugiat semper. Nulla sit amet dolor ligula. Suspendisse vitae convallis neque, at varius neque. Sed vitae elit nec justo porttitor dictum ornare id mauris. Donec condimentum, felis id condimentum efficitur, tortor mauris rhoncus metus, non sollicitudin ante ipsum in mi. Sed tellus tortor, consequat ut fermentum eget, aliquet sit amet nisl. Pellentesque augue lacus, commodo vitae leo vel, pulvinar faucibus metus. Nullam pellentesque lacus felis, ut lacinia justo ullamcorper at. Aliquam vulputate dolor eros, eget volutpat libero feugiat eu. In vitae viverra purus. Suspendisse velit elit, tincidunt lacinia tristique nec, interdum in sem. Vestibulum blandit a mauris tristique eleifend.

Ut ultrices auctor lacus. Mauris molestie eget elit et dignissim. Phasellus auctor bibendum pulvinar. Nam a ante nibh. Fusce aliquam placerat vestibulum. Nam posuere sodales sem, in vestibulum purus ultricies a. Vivamus ut cursus sapien, a pharetra tortor. Sed sed iaculis libero, id tincidunt ipsum. Vivamus fringilla eros tempor fringilla mattis. Nam bibendum faucibus lorem, non pellentesque nulla elementum et. Integer in felis elit. Curabitur sollicitudin bibendum luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur efficitur enim quam.`

export default ipsum;